spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mall_tiny?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
  redis:
    host: 192.168.150.130 # Redis服务器地址
    database: 0 # Redis数据库索引（默认为0）
    port: 6379 # Redis服务器连接端口
    password: # Redis服务器连接密码（默认为空）
    timeout: 3000ms # 连接超时时间（毫秒）

logging:
  level:
    root: info
    com.alvin: debug

aliyun:
  oss:
    endpoint: oss-cn-beijing.aliyuncs.com # oss对外服务的访问域名
    accessKeyId: LTAI5t74LKafBDL9vowxnC8V # 访问身份验证中用到用户标识
    accessKeySecret: qHvgac4UbXXXkstR2f7Wns2RDolVlf # 用户用于加密签名字符串和oss用来验证签名字符串的密钥
    bucketName: alvin-mall # oss的存储空间
    policy:
      expire: 300 # 签名有效期(S)
    maxSize: 10 # 上传文件大小(M)
    #callback:  # 文件上传成功后的回调地址
    dir:
      prefix: alvin/images/ # 上传文件夹路径前缀
